import "./globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(GeistSans.className, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
